### ISSUE TITLE
Index.html uses possibly proprietary code

### ISSUE THREAD

**Issue by nmoskopp** [LeToteTeam/kiosk_system_rpi3#17]
`kiosk_system_rpi3/rootfs_overlay/var/www/index.html` uses code from https://www.w3schools.com/graphics/game_intro.asp – however, that site says `Copyright 1999-2018 by Refsnes Data. All Rights Reserved.`. Should this code be removed?

**Comment by mobileoverlord** [comment]
Fixed in 1.0.0-rc.0 The code was removed from the main system repo. The example project has a lite demo page.
