### ISSUE TITLE
No error handling when determining NERVES_FW_VCS_IDENTIFIER

### ISSUE THREAD

**Issue by nmoskopp** [LeToteTeam/kiosk_system_rpi3#18]
In `kiosk_system_rpi3/mix.exs`, the line `:os.cmd('git rev-parse HEAD')` does not check the return code, possibly setting the environment variable `NERVES_FW_VCS_IDENTIFIER` to the value `fatal: Not a git repository (or any of the parent directories): .git` if executed outside a Git repository.

I think this line should use `System.cmd("git", ["rev-parse", "HEAD"])` instead, which returns `{"", 128}` in this specific error case.

**Comment by mobileoverlord** [comment]
Yeah, I knew this would eventually come to bite me. I think we could just omit this and let circle bake it into the releases.

**Comment by mobileoverlord** [comment]
this was in there when the repo was not on hex yet, I think I am just going to remove it.

**Comment by mobileoverlord** [comment]
Fixed in 1.0.0-rc.0
