### ISSUE TITLE
Use .ssh/authorized_keys instead of .ssh/id_rsa.pub

### ISSUE THREAD

**Issue by nmoskopp** [LeToteTeam/kiosk_system_rpi3#19]
In `kiosk_system_rpi3/example/config/config.exs`, there exists the following block of code:
```
config :nerves_firmware_ssh,
  authorized_keys: [
    File.read!(Path.join(System.user_home!, ".ssh/id_rsa.pub"))
  ]
```
I believe this code should be changed so that it reads the authorized keys for SSH from `.ssh/authorized_keys` like other SSH tools instead of hardcoding the path to a single RSA key.

**Comment by mobileoverlord** [comment]
This is more of an issue to be presented over on nerves_firmware_ssh about how we should go about adding authorized keys. However, this list is to configure the node for which keys are authorized for pushing firmware updates to it. If you select the file from the host, it wouldn;t contain the hosts own public key.
