### ISSUE TITLE
Possibility of a Raspberry Pi 2 version of the Kiosk System?

### ISSUE THREAD

**Issue by Qqwy** [LeToteTeam/kiosk_system_rpi3#20]
Hello there!

This looks like a really interesting project, but unfortunately I only have a Raspberry Pi 2. How difficult would it be to port this target over to the Rpi2?

**Comment by mobileoverlord** [comment]
It is certainly possible to port this to run on raspberry pi 2, however, the browser will be a lot slower. At petite we only use raspberry pi 3 and 3b+. There is documentation on Nerves project on how to create custom systems. I would start by forking the rpi2 system and then adding back the custom bits of config from this one.

**Comment by Qqwy** [comment]
In this case, I am mostly looking at building a photobooth using the Raspberry Pi, so I don't think that it is a problem if the browser is somewhat slower.

I'll look into creating a custom target using the extra bits of config from this package :-)

**Comment by mobileoverlord** [comment]
Sorry for being initially brief, I’m currently mobile. Here is the doc that I was referring to https://hexdocs.pm/nerves/1.0.0-rc.1/systems.html#customizing-your-own-nerves-system

**Comment by Qqwy** [comment]
No problem! I'm really happy with how quick you have responded! :relaxed:
