### ISSUE TITLE
Upgrade nerves_system_br to 1.3.0

### ISSUE THREAD

**Issue by tooreht** [LeToteTeam/kiosk_system_rpi3#23]
I would really like to see an upgrade to Erlang 21.0.

**Comment by mobileoverlord** [comment]
I agree, I am in the process of releasing the nerves_system_* repositories with the nerves_system_br 1.3.0 update. The kiosk repos are going to take a little more work and depend on fixing this https://github.com/LeToteTeam/kiosk_system_rpi3/issues/22.

**Comment by mobileoverlord** [comment]
merged into master

**Comment by tooreht** [comment]
Awesome, thank you!
