### ISSUE TITLE
Super slow firmware build

### ISSUE THREAD

**Issue by epinault** [LeToteTeam/kiosk_system_rpi3#38]
A similar issue was fixed in the elixir conf 2018 where it was slow to build a firmware .

The issue is in the merge-squashfs . 

Combining sed -e improve the speed drastically instead of piping them to each othersW  would love to prove the patch if you can point me to the file ? Cannot seem to find it in this repo

**Comment by mobileoverlord** [comment]
A lot of these would be from nerves_system_br, an updated version would probably suffice. I’ll see if I can find a commit.

**Comment by epinault** [comment]
yup! https://github.com/nerves-project/nerves_system_br/pull/233/files

this is the one that need refresh on that :)

**Comment by epinault** [comment]
i locally patched it and worked all good :) thanks for the great work you guys do!

**Comment by mobileoverlord** [comment]
This should be fixed with the latest build.
