### ISSUE TITLE
Update to latest nerves_system_rpi3/nerves_system_br

### ISSUE THREAD

**Issue by fhunleth** [LeToteTeam/kiosk_system_rpi3#39]
Sadly, this will require some testing, but the latest has some good stuff:

1. Faster builds - See #38 
2. Scrubber fixes that will detect architecture mismatches on the kiosk app
3. Linux 4.14

I'll help if you need it.

**Comment by mobileoverlord** [comment]
v 1.4.0 supports nerves_system_br 1.6.5
