### ISSUE TITLE
How to actually launch the kiosk browser?

### ISSUE THREAD

**Issue by orestis** [LeToteTeam/kiosk_system_rpi3#5]
I have finally successfully built the image, only to realise I now need to control the browser.

I tried to add this to my nerves app:

```
def run_kiosk do
    System.cmd("qt-webkit-kiosk", ["--clear-cache", "-u", "http://localhost"])
  end
```

And wrap it into a supervisor with:

```
worker(Task, [fn -> run_kiosk end]),
```

But upon system boot the erlang VM crashes, so it probably doesn't do what it's supposed to do.

Thanks in advance for any help!

**Comment by electricshaman** [comment]
@orestis Did my comments in #12 help resolve this issue for you?
